#!/usr/bin/env python3

import os
import unittest
import requests
import warnings
from container import Container
from rmlmapper import RMLMapper
from postgresql import PostgreSQL
from mysql import MySQL
from virtuoso import Virtuoso
from time import sleep
from rdflib import Graph

DATA_DIR = os.path.join(os.getcwd(), 'data')

class Tests(unittest.TestCase):
    def setUp(self):
        warnings.filterwarnings(action="ignore", message="unclosed", category=ResourceWarning)

    def test_docker_run(self):
        c = Container('nginx:alpine', 'test_docker_run', {'80/tcp': '8080/tcp'})
        c.run()
        sleep(5)
        r = requests.get('http://localhost:8080')
        self.assertEqual(r.status_code, 200)
        r.raise_for_status()
        c.stop()

    def test_docker_run_and_wait_for_log(self):
        c = Container('nginx:alpine', 'test_docker_run_and_wait_for_log',
                      {'80/tcp': '8081/tcp'})
        c.run_and_wait_for_log('start worker process')
        r = requests.get('http://localhost:8081')
        self.assertEqual(r.status_code, 200)
        r.raise_for_status()
        c.stop()

    def test_rmlmapper(self):
        rmlmapper = RMLMapper(DATA_DIR)
        rmlmapper.execute(['-m', '/data/mapping.rml.ttl', '-s', 'nquads',
                           '-o', '/data/out.nq'])
        self.assertTrue(os.path.exists('data/out.nq'))
        g = Graph()
        g.parse('data/out.nq', format='nquads')
        self.assertEqual(len(g), 3)
        rmlmapper.stop()

    def test_postgresql(self):
        postgresql = PostgreSQL(DATA_DIR)
        postgresql.wait_until_ready()
        # Perform query?
        postgresql.stop()

    def test_mysql(self):
        mysql = MySQL(DATA_DIR)
        mysql.wait_until_ready()
        # Perform query?
        mysql.stop()

    def test_virtuoso(self):
        virtuoso = Virtuoso(DATA_DIR)
        virtuoso.wait_until_ready()

        # Check if web interface is up
        r = requests.get('http://localhost:8890')
        self.assertEqual(r.status_code, 200)
        r.raise_for_status()

        # Check if iSQL is up, HTTP is unsupported on the iSQL port
        # so the connection will be closed without a response
        with self.assertRaises(requests.exceptions.ConnectionError) as e:
            r = requests.get('http://localhost:1111')
            r.raise_for_status()
        self.assertTrue('Connection aborted' in str(e.exception))

        virtuoso.stop()

if __name__ == '__main__':
    unittest.main()
